apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: influx
  name: influx-config
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/med4all/influx
      versionId: e38fe57a-81d8-4b04-8d88-dc038c88f21e
