apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: influx
  name: influx-config
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/med4all/influx
      versionId: AWSCURRENT
