apiVersion: apps/v1
kind: Deployment
metadata:
  name: med4all-site
  namespace: default
spec:
  selector:
    matchLabels:
      app: med4all-site
  replicas: 3
  template:
    metadata:
      labels:
        app: med4all-site
    spec:
      containers:
        - name: med4all-site-pod
          image: 607128906826.dkr.ecr.ap-southeast-1.amazonaws.com/med4all-site:v0.0.2
          ports:
            - containerPort: 8000

          env:
            - name: ENV
              value: prod