apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: risk-score-secret
  name: risk-score-secret-config
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: dev/med4all/risk-score
      versionId: 8640d9f2-bb7d-47f0-9042-e51018332b48
