apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: risk-score-secret
  name: risk-score-secret-config
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/med4all/risk-score
      versionId: 5c104290-da9c-4565-b795-ea373f6275e4
