apiVersion: apps/v1
kind: Deployment
metadata:
  name: med4all-waiting-list-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: med4all-waiting-list-agent
  replicas: 3
  template:
    metadata:
      labels:
        app: med4all-waiting-list-agent
    spec:
      containers:
        - name: med4all-waiting-list-agent-pod
          image: 607128906826.dkr.ecr.ap-southeast-1.amazonaws.com/med4all-waiting-list-agent:v0.0.2

          env:
            - name: BROKER_LIST
              value: b-1.med4all-msk-clust.kh3jrm.c3.kafka.ap-southeast-1.amazonaws.com:9094,b-2.med4all-msk-clust.kh3jrm.c3.kafka.ap-southeast-1.amazonaws.com:9094,b-3.med4all-msk-clust.kh3jrm.c3.kafka.ap-southeast-1.amazonaws.com:9094
            - name: GROUP_ID
              value: med4all-waiting-list-agent
            - name: WAITING_LIST_API_URL
              value: http://localhost:8999/ps/patient/create
