apiVersion: apps/v1
kind: Deployment
metadata:
  name: med4all-waiting-list-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: med4all-waiting-list-agent
  replicas: 3
  template:
    metadata:
      labels:
        app: med4all-waiting-list-agent
    spec:
      containers:
        - name: med4all-waiting-list-agent-pod
          image: 607128906826.dkr.ecr.ap-southeast-1.amazonaws.com/med4all-waiting-list-agent:v0.2.11

          env:
            - name: KAFKA_BROKER_LIST
              value: b-1.med4all-msk-clust.zvxx2j.c3.kafka.ap-southeast-1.amazonaws.com:9094,b-2.med4all-msk-clust.zvxx2j.c3.kafka.ap-southeast-1.amazonaws.com:9094,b-3.med4all-msk-clust.zvxx2j.c3.kafka.ap-southeast-1.amazonaws.com:9094
            - name: KAFKA_GROUP_ID
              value: med4all-waiting-list-agent
            - name: WAITING_LIST_API_URL
              value: https://covid-waiting-list-y6gdj3xoga-as.a.run.app/api/upsert
            - name: WAITING_LIST_API_KEY
              valueFrom:
                secretKeyRef:
                  name: waiting-list-api-key-config
                  key: waiting-list-api-key
