apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: waiting-list-api-key-config
  name: waiting-list-api-key-config
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/med4all/waiting-list-api-key
      versionId: 7dbb2740-c9ce-4786-8605-9f2e0e4ad1b7
