apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: waiting-list-api-key-config
  name: waiting-list-api-key-config
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/med4all/waiting-list-api-key
      versionId: f2645b17-f271-40f2-bec5-91c65704cde0
