apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: med4all-patient-api
  name: secret-key
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: dev/med4all/patient-api-secret-key
      versionId: 9d1c6e7e-4aba-4d72-a3d0-e87ca1c8e419
