apiVersion: apps/v1
kind: Deployment
metadata:
  name: med4all-be
  namespace: default
spec:
  selector:
    matchLabels:
      app: med4all-be
  replicas: 3
  template:
    metadata:
      labels:
        app: med4all-be
    spec:
      containers:
        - name: med4all-be-pod
          image: 607128906826.dkr.ecr.ap-southeast-1.amazonaws.com/med4all-be:v0.30.10
          ports:
            - containerPort: 8000

          env:
            - name: ENV
              value: dev

            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-secret
                  key: aws_access_key_id

            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-access-secret
                  key: aws_secret_access_key

            - name: NEXMO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nexmo-access-key
                  key: api-key

            - name: NEXMO_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: nexmo-access-key
                  key: api-secret

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-access-key
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-access-key
                  key: password

            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: med4all-be
                  key: jwt-secret-key

            - name: COLINK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: colink
                  key: colink-token
