apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: med4all-be
  name: aws-access-secret
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: dev/aws/secret
      versionId: 19413052-6119-4168-9b8b-e4598f922d4f

---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: med4all-be
  name: nexmo-access-key
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: dev/nexmo
      versionId: 2d1ddbb9-ed38-4c8d-ba99-b31e1fd64206

---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: med4all-be
  name: rds-access-key
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: dev/med4all/postgres
      versionId: 3c25f814-a020-46c3-a6a2-9491b43e73bd

---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: med4all-be
  name: med4all-be
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: dev/med4all-be
      versionId: 3c2a08c4-aba0-4f6a-b8a5-96003b1a3874

---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: med4all-be
  name: colink
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: dev/colink
      versionId: 8eac3cd8-d3a4-4d7c-a29a-b832d7bafd5f
