apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: med4all-be
  name: aws-access-secret
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/aws/secret
      versionId: 228e9c82-80ae-4a83-b5c8-7832d0e864ee

---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: med4all-be
  name: nexmo-access-key
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/nexmo
      versionId: 820f7e50-7f70-43a1-97ef-f40e00f025ce
