apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: med4all-be
  name: aws-access-secret
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/aws/secret
      versionId: a251b48c-db2b-42c8-af97-c9c339351b80

---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: med4all-be
  name: nexmo-access-key
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/nexmo
      versionId: 820f7e50-7f70-43a1-97ef-f40e00f025ce

---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: med4all-be
  name: rds-access-key
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/med4all/postgres
      versionId: c1861d51-9a8a-4ec1-912d-46bc5ebb08ae

---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: med4all-be
  name: med4all-be-config-v1.0.0
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/med4all-be
      versionId: 79fc3af4-17ca-4b96-a87e-19ff2e0eb65e

---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: med4all-be
  name: colink-v1.0.0
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/colink
      versionId: 40474661-ab1b-404e-8539-42574578f2f0