apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: aws-secret
  name: aws-secret-config
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/aws/secret
      versionId: 228e9c82-80ae-4a83-b5c8-7832d0e864ee
