apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: postgres
  name: postgres-config
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/med4all/postgres
      versionId: c1861d51-9a8a-4ec1-912d-46bc5ebb08ae
