apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: postgres
  name: postgres-config
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: dev/med4all/postgres
      versionId: 3c25f814-a020-46c3-a6a2-9491b43e73bd
