apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: postgres
  name: postgres-config
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/med4all/postgres
      versionId: 19e75df8-8550-47d8-88a1-92275ff87452
---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: influx
  name: influx-config
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/med4all/influx
      versionId: e02657e2-deb7-48f6-bded-e1e69152bf7d
