apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: api.gu-aeng.ninja
      http:
        paths:
          - path: /banana/?(.*)
            pathType: Prefix
            backend:
              service:
                name: banana-service
                port:
                  number: 5678
