apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd-deployment
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: fluentd-logs
    name: arn:aws:eks:ap-southeast-1:950124295708:cluster/med4all-eks-cluster
  project: default
  source:
    path: fluentd
    repoURL: https://github.com/gu-tum-gun-aeng/med4all-deployment
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true