apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit-deployment
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: logging-producer
    name: arn:aws:eks:ap-southeast-1:607128906826:cluster/med4all-eks-cluster-dev
  project: default
  source:
    path: fluentbit-producer
    repoURL: https://github.com/gu-tum-gun-aeng/med4all-deployment
    targetRevision: develop
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true