apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: med4all-patient-api
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: arn:aws:eks:ap-southeast-1:607128906826:cluster/med4all-eks-cluster-dev
  project: default
  source:
    path: med4all-patient-api
    repoURL: https://github.com/gu-tum-gun-aeng/med4all-deployment
    targetRevision: develop
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
