apiVersion: apps/v1
kind: Deployment
metadata:
  name: med4all-be
  namespace: default
spec:
  selector:
    matchLabels:
      app: med4all-be
  replicas: 3
  template:
    metadata:
      labels:
        app: med4all-be
    spec:
      containers:
        - name: med4all-be-pod
          image: 950124295708.dkr.ecr.ap-southeast-1.amazonaws.com/med4all-be:v0.2.2
          ports:
            - containerPort: 8000
