apiVersion: apps/v1
kind: Deployment
metadata:
  name: med4all-external-routing-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: med4all-external-routing-agent
  replicas: 3
  template:
    metadata:
      labels:
        app: med4all-external-routing-agent
    spec:
      containers:
        - name: med4all-external-routing-agent-pod
          image: 607128906826.dkr.ecr.ap-southeast-1.amazonaws.com/med4all-external-routing-agent:v0.0.28

          env:
            - name: KAFKA_BROKER_LIST
              value: b-1.med4all-msk-clust.kh3jrm.c3.kafka.ap-southeast-1.amazonaws.com:9094,b-2.med4all-msk-clust.kh3jrm.c3.kafka.ap-southeast-1.amazonaws.com:9094,b-3.med4all-msk-clust.kh3jrm.c3.kafka.ap-southeast-1.amazonaws.com:9094
            - name: KAFKA_GROUP_ID
              value: med4all-external-routing-agent
            - name: COLINK_API_URL
              value: https://api-cl.gbdi.cloud/api/api/backend/hotline/insert-records
            - name: WISIBLE_API_URL
              value: https://api-covid.wisible.com/v2/addPatient
            - name: COLINK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: external-routing-agent-api-key-config
                  key: colink-token
            - name: WISIBLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: external-routing-agent-wisible-config
                  key: x-api-key
            - name: WISIBLE_COOKIE
              valueFrom:
                secretKeyRef:
                  name: external-routing-agent-wisible-config
                  key: cookie
