apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: external-routing-agent-api-key-config
  name: external-routing-agent-api-key-config
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/colink
      versionId: 40474661-ab1b-404e-8539-42574578f2f0
---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: external-routing-agent-wisible-config
  name: external-routing-agent-wisible-config
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: dev/wisible
      versionId: b9176252-12fd-4a3b-88d4-a1bd4e72ca79