apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  labels:
    app: external-routing-agent-api-key-config
  name: external-routing-agent-api-key-config
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: dev/colink
      versionId: 8eac3cd8-d3a4-4d7c-a29a-b832d7bafd5f